version: '3.7'
services:
  locust_master:
    build:
      context: .
      target: test
    ports:
     - "8089:8089"
    environment:
     - ENV=local
    env_file: 
      - local_conf/locust.conf
    volumes:
      - .:/test
    entrypoint: locust --host=<HOST>

  locust_worker:
    build:
      context: .
      target: test
    environment:
    - ENV=local
    env_file: 
      - local_conf/locust.conf
    volumes:
      - .:/test
    entrypoint: locust --worker --master-host locust_master

  # cadvisor:
  #   image: google/cadvisor:latest
  #   container_name: cadvisor
  #   ports:
  #       - 8080:8080
  #   privileged: true
  #   volumes:
  #       - /:/rootfs:ro
  #       - /var/run:/var/run:rw
  #       - /sys:/sys:ro
  #       - /var/lib/docker/:/var/lib/docker:ro



  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #       - 9090:9090
  #   command:
  #       - --config.file=/etc/prometheus/prometheus.yaml
  #   volumes:
  #       - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro


  # grafana:
  #       image: grafana/grafana
  #       container_name: grafana
  #       ports:
  #           - "3000:3000"
  #       volumes:
  #           - ./grafana.ini:/etc/grafana/grafana.ini
  #           - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
  #       depends_on:
  #           - prometheus
